name:                machine-learning-haskell
version:             0.1.0.0
github:              "oliegjio/machine-learning-haskell"
author:              "oliegjio"
maintainer:          "oliegjio@gmail.com"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  machine-learning-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - machine-learning-haskell

tests:
  machine-learning-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - machine-learning-haskell
